[tool.pycln]
all = false
expand_stars = false
skip_imports = [
  # Star imported C wrapped modules
  "_winxptheme",
  "dde",
  "odbc",
  "win32api",
  "win32clipboard",
  "win32event",
  "win32file",
  "win32gui",
  "win32inet",
  "win32pipe",
  "win32ras",
  "winxpgui",
  # imports with side-effects
  "win32ui",  # Must be imported to resolve: ImportError: This must be an MFC application
  "win32traceutil",  # Sets up trace collector
]
